pipeline {
   agent {
    node {
        label 'agent1'
    }
    }
    options {
        timeout(time: 1, unit: 'HOURS') 
        disableConcurrentBuilds()
         ansiColor('xterm')
    }
     parameters {
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    
    stages {
       
        stage('init') {
            steps {
                sh """
                   cd 0-vpc
                   terraform init -reconfigure
                """
            }
        }
        stage('plan') {
            steps {
                sh """
                   cd 0-vpc
                   terraform plan 
                """
            }
        }
        stage('deploy') {
            when
            {
               "${params.action}" == "apply"
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                sh """
                   cd 0-vpc
                   terraform apply -auto-approve
                """
            }
        }
        stage('destroy')
        {
           when
           {
            "${params.action}" == "destroy"
           }
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                sh """
                   cd 0-vpc
                   terraform destroy -auto-approve
                """
            }

        }
    }
     post { 
        always { 
            echo 'I will always say Hello again!'
            
        }
     }

    }  
    
