pipeline {
   agent {
    node {
        label 'agent1'
    }
    }
    options {
        timeout(time: 1, unit: 'HOURS') 
        disableConcurrentBuilds()
         ansiColor('xterm')
    }
    
    
    stages {
       
        stage('init') {
            steps {
                sh """
                   cd 0-vpc
                   terraform init -reconfigure
                """
            }
        }
        stage('plan') {
            steps {
                sh """
                   cd 0-vpc
                   terraform plan 
                """
            }
        }
        stage('apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                sh """
                   cd 0-vpc
                   terraform apply -auto-approve
                """
            }
        }
        
    }
     post { 
        always { 
            echo 'I will always say Hello again!'
            
        }
     }

    }  
    
